openapi: '3.0.0'
info:
  title: TapDesk REST API
  version: '2.0'
servers:
  - url: /
    description: 当前环境
  - url: http://127.0.0.1:4000
    description: 开发环境
components:
  securitySchemes:
    Session token:
      type: apiKey
      in: header
      name: x-lc-session
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        nickname:
          type: string
        avatarUrl:
          type: string
    Group:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        parentId: 
          type: string
        position:
          type: number
        active: 
          type: boolean
        template:
          type: string
    File:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        mime:
          type: string
        url:
          type: string
    Evaluation:
      type: object
      properties:
        star:
          type: integer
        content:
          type: string
    Ticket:
      type: object
      properties:
        id:
          type: string
        nid:
          type: integer
        title:
          type: string
        categoryId:
          type: string
        categoryPath:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
        authorId:
          type: string
        author:
          $ref: '#/components/schemas/User'
        assigneeId:
          type: string
        assignee:
          $ref: '#/components/schemas/User'
        groupId:
          type: string
        group:
          $ref: '#/components/schemas/Group'
        files:
          type: array
          items:
            $ref: '#/components/schemas/File'
        status:
          $ref: '#/components/schemas/Status'
        evaluation:
          $ref: '#/components/schemas/Evaluation'
        replyCount:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Status:
      type: integer
      enum: [50, 120, 160, 220, 250, 280]
    Notification:
      type: object
      properties:
        id:
          type: string
        ticket:
          $ref: '#/components/schemas/Ticket'
        unreadCount:
          type: number
        latestAction:
          type: string
          enum: ['newTicket', 'reply', 'changeAssignee', 'ticketEvaluation', 'changeStatus']
        latestActionAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Article:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        contentSafeHTML:
          type: string
        private:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Revision:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        comment:
          type: string
        meta:
          type: boolean
        private:
          type: boolean
        author:
          $ref: '#/components/schemas/User'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
security:
  - Session token: []
paths:
  /api/2/tickets:
    get:
      tags: [Ticket]
      summary: 查询工单
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          description: 页数，范围：[1, Infinity)
        - name: pageSize
          in: query
          schema:
            type: integer
          description: 每页数量，范围：[0, 100]，默认为 10
        - name: count
          in: query
          schema:
            type: boolean
          description: 为 `true` 时通过 x-total-count 返回符合条件的工单数量
        - name: authorId
          in: query
          schema:
            type: string
          description: 工单创建者 ID
        - name: assigneeId
          in: query
          schema:
            type: string
          description: 工单负责人 ID，多个值可用 `,` 分隔。`null` 表示未分配负责人
        - name: groupId
          in: query
          schema:
            type: string
          description: 客服组 ID，多个值可用 `,` 分隔。`null` 表示未分配客服组
        - name: categoryId
          in: query
          schema:
            type: string
          description: 分类 ID，多个值可用 `,` 分隔
        - name: rootCategoryId
          in: query
          schema:
            type: string
          description: 根分类 ID，等同于将 categoryId 设置为 rootCategoryId + 其下所有子分类的 ID
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/Status'
        - name: evaluation.star
          in: query
          schema:
            type: integer
            enum: [0, 1]
          description: 评价星级
        - name: createdAt
          in: query
          schema:
            type: string
          description: |
            创建时间的范围，格式为：`{starts}..{ends}`，缺省值用 `*` 表示：

            `2021-09-01T00:00:00.000..*`

            `*..2021-09-30T23:59:59.999`

            `2021-09-01T00:00:00.000..2021-09-30T23:59:59.999`
        - name: orderBy
          in: query
          schema:
            type: string
            enum:
              - createdAt
              - createdAt-desc
              - updatedAt
              - updatedAt-desc
              - latestCustomerServiceReplyAt
              - latestCustomerServiceReplyAt-desc
              - status
              - status-desc
          description: 排序字段，默认为升序，`-desc` 后缀表示降序
        - name: include
          in: query
          schema:
            type: string
          description: |
            将指定字段包含进查询结果中。可选值：
            - author
            - assignee
            - category
            - categoryPath
            - group（仅客服可用）
            - files
            - unreadCount

            多个值可用 `,` 分隔
        - name: includeMetaKeys
          in: query
          schema:
            type: string
          description: 将指定 metaData 字段包含进查询结果中，多个值可用 `,` 分隔。
        - name: where
          in: query
          schema:
            type: string
          description: 底层查询条件，格式为 JSON 字符串。详见 [LeanCloud REST API 文档](https://leancloud.cn/docs/rest_api.html)
      responses:
        '200':
          description: OK
          headers:
            x-total-count:
              schema:
                type: string
                format: integer
              description: 符合条件的工单数量
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'
  /api/2/tickets/{id}/replies:
    parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
    post:
      tags: [ticket]
      summary: 创建回复
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                fileIds:
                  type: array
                  items:
                    type: string
                internal:
                  type: boolean
                  description: 创建为内部回复（仅客服可见，该参数仅客服有效）
              required: [content]
            examples:
              创建普通回复:
                value:
                  content: '你们给我搞的这个客服系统啊——Excited!'
              创建带附件的回复:
                value:
                  content: '如图所示'
                  fileIds: ['uploaded-file-id']
              创建仅客服可见的回复:
                value:
                  content: '这个用户老是提一些莫名其妙的问题 😑'
                  internal: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  content:
                    type: string
                  contentSafeHTML:
                    type: string
                  author:
                    $ref: '#/components/schemas/User'
                  isCustomerService:
                    type: boolean
                  files:
                    type: array
                    items:
                      $ref: '#/components/schemas/File'
                  createdAt:
                    type: string
                    format: date-time
                  updatedAt:
                    type: string
                    format: date-time
  /api/2/unread:
    get:
      tags: ['Notification']
      summary: 获取当前用户是否有未读的通知
      description: 通常用于判断是否要显示小红点
      responses:
        '200':
          description: 返回 true / false
          content:
            application/json:
              schema:
                type: boolean
  /api/2/notifications:
    get:
      tags: ['Notification']
      summary: 获取当前用户工单更新通知
      parameters:
        - name: unread
          in: query
          schema:
            type: string
          description: 如该参数出现（值可以任意指定），则仅返回未读的通知
        - name: before
          in: query
          schema:
            type: string
            description: ISO 时间戳，配合返回值中的 latestActionAt 翻页
        - name: limit
          in: query
          schema:
            type: number
            description: 每页条数，默认 25，最大 999
        - name: includeTicketMetaKeys
          in: query
          schema:
            type: string
            description: 在返回结果的 ticket 包含的 metaData 字段列表，多个值用 `,` 分隔
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
  /api/2/notifications/read-all:
    post:
      tags: ['Notification']
      summary: 批量将所有未读通知标为已读
      responses:
        '200':
          description: Done

  /api/2/articles:
    get:
      tags: ['Knowladge base']
      summary: 查询文章
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          description: 页数，范围：[1, Infinity)
        - name: pageSize
          in: query
          schema:
            type: integer
          description: 每页数量，范围：[0, 100]，默认为 20
        - name: private
          in: query
          schema:
            type: boolean
          description: 指定仅返回 private / public 的文章，仅对客服账号生效（用户仅能看到 public 的文章）
        - name: count
          in: query
          schema:
            type: boolean
          description: 为 `true` 时通过 x-total-count 返回符合条件的工单数量
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
    post:
      tags: ['Knowladge base']
      summary: 创建文章
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                private:
                  type: boolean
              required: [title, content]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Article'

  /api/2/articles/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
    get:
      tags: ['Knowladge base']
      summary: 获取文章
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
    patch:
      tags: ['Knowladge base']
      summary: 更新文章
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                private:
                  type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
    delete:
      tags: ['Knowladge base']
      summary: 删除文章
      description: 已上线（public）的文章不可删除，使用中（有关联的分类）的文章不可删除。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /api/2/articles/{id}/categories:
    parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
    get:
      tags: ['Knowladge base']
      summary: 获取关联了该文章为常见问题或公告的分类
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

  /api/2/articles/{id}/revisions:
    parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      - name: page
        in: query
        schema:
          type: integer
        description: 页数，范围：[1, Infinity)
      - name: pageSize
        in: query
        schema:
          type: integer
        description: 每页数量，范围：[0, 100]，默认为 20
      - name: meta
        in: query
        schema:
          type: boolean
        description: 为真时仅返回发布、撤销发布记录，为假时仅返回内容修改记录
      - name: count
        in: query
        schema:
          type: boolean
        description: 为 `true` 时通过 x-total-count 返回符合条件的工单数量
    get:
      tags: ['Knowladge base']
      summary: 获取文章修改记录
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Revision'
